# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - 3.5

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_KEY
  keep-history: true
  on:
    branch: master
