# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - 3.5

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

deploy:
  provider: releases
  skip-cleanup: true
  api-key: $GH_KEY
  keep-history: true
  file: testrcicd_0.1.0.tar.gz
